### ISSUE TITLE
plateau: test of :i18nyaml: construct in document.adoc for over-riding modspec table header translations

### ISSUE THREAD

**Issue by ReesePlews** [metanorma/mn-samples-plateau#284]
as described in https://github.com/ReesePlews/ribose_discussions/issues/27 this will be a test on github to see if the outlined procedures work.  as mentioned in the original issue i was not able to get this to work locally. i will try in github.

i have added this line to the document.adoc file
`
:i18nyaml: config/plateau_i18n-ja.yaml
`
the `plateau_i18n-ja.yaml` file is in the config folder which is at the same level as `document.adoc`.

here is the `plateau_i18n-ja.yaml` file:  
(**NOTE: 2025-01-06 this file is now old; the revised file is shown in a later comment.**)

```
requirements:
   default:
     requirement: 要件
     recommendation: 推奨
     permission: 許可
     obligation: 義務
     subject: 主題
     inherits: 継承
   modspec:
     recommendationtest: 推奨検証
     requirementtest: 要件検証
     permissiontest: 許可検証
     recommendationclass: 要求分類
     requirementclass: 要求分類
     permissionclass: 許可分類
     abstracttest: 抽象検証
     conformanceclass: 適合分類
     conformancetest: 適合性検証
     targettype: 対象の種類
     target: 対象
     testpurpose: 検証目的
     testmethod: 検証方法
     dependency: 前提条件
     indirectdependency: 間接的な前提条件
     identifier: ID
     included_in: 分類
     statement: 明文
     description: 説明
     guidance: ガイダンス
     implements: 実装
     provision: 規定
```

**Comment by kwkwan** [comment]
Hi @ReesePlews , should ` recommendationclass` be translated into `推奨分類` instead of `要求分類`?

**Comment by ReesePlews** [comment]
hello @kwkwan a very happy new year to you! thanks for checking these things during the holidays. i received these translations from the Plateau Team and i did not check them because they were from a native speaker.  if this external table feature can work, updates to the table can be made more easily.   Wa, thank you again for checking this issue and the translation. 

i will request @AIS-RyoMukai to have a look at the translations again and make any revisions here. i will then update the file if there are any revisions. thank you Mukai-san.

**Comment by ReesePlews** [comment]
hello @kwkwan i have heard from the Plateau Team and yes, there was a problem which you pointed out. 

```
     recommendationclass: 要求分類
     requirementclass: 要求分類
　　　　↓
     recommendationclass: 推奨分類
     requirementclass: 要件分類
```


the revised translations are shown here:


```
requirements:
   default:
     requirement: 要件
     recommendation: 推奨
     permission: 許可
     obligation: 義務
     subject: 主題
     inherits: 継承
   modspec:
     recommendationtest: 推奨検証
     requirementtest: 要件検証
     permissiontest: 許可検証
     recommendationclass: 推奨分類
     requirementclass: 要件分類
     permissionclass: 許可分類
     abstracttest: 抽象検証
     conformanceclass: 適合分類
     conformancetest: 適合性検証
     targettype: 対象の種類
     target: 対象
     testpurpose: 検証目的
     testmethod: 検証方法
     dependency: 前提条件
     indirectdependency: 間接的な前提条件
     identifier: ID
     included_in: 分類
     statement: 明文
     description: 説明
     guidance: ガイダンス
     implements: 実装
     provision: 規定
```

**Comment by ReesePlews** [comment]
hi @ronaldtse

question: earlier you said i needed to be inside of the folder to run this, but i recall there was the update to enable a relative path. even with that relative path, perhaps i should be in the sources/002-v5 folder, or am i not specifying the path correctly?

after the fix which is the correct usage?

method 1) :i18nyaml: sources/002-v5/config/plateau_i18n-ja.yaml
( _i confirmed with a local install this works_ )
or
method 2) :i18nyaml: config/plateau_i18n-ja.yaml
( _this does not seem to work (shown below), is that the expected usage after the fix? or am doing something wrong?_ )

 i am trying to test this locally after doing a bundle update i am running this command:

`PS E:\github\mn-samples-plateau> bundle exec metanorma sources/002-v5/document.adoc`

using method 2 but the following error occurs:

```
asciidoctor: ERROR: <stdin>: line 14641: dropping cells from incomplete row detected end of table
Fatal Error: No such file or directory @ rb_sysopen - config/plateau_i18n-ja.yaml
C:/tools/ruby33/lib/ruby/gems/3.3.0/gems/psych-5.2.2/lib/psych.rb:688:in `initialize': No such file or directory @ rb_sysopen - config/plateau_i18n-ja.yaml (Errno::ENOENT)
        from C:/tools/ruby33/lib/ruby/gems/3.3.0/gems/psych-5.2.2/lib/psych.rb:688:in `open'
        from C:/tools/ruby33/lib/ruby/gems/3.3.0/gems/psych-5.2.2/lib/psych.rb:688:in `load_file'
```

bundle list

PS E:\github\mn-samples-plateau> bundle list
```
Gems included by the bundle:
  * activesupport (8.0.1)
  * addressable (2.8.7)
  * algolia (2.3.4)
  * arr-pm (0.0.12)
  * asciidoctor (2.0.23)
  * asciimath (2.0.5)
  * asciimath2unitsml (0.4.4)
  * base64 (0.2.0)
  * bcp47_spec (0.2.1)
  * benchmark (0.4.0)
  * bibtex-ruby (6.1.0)
  * bigdecimal (3.1.9)
  * builder (3.3.0)
  * camertron-eprun (1.1.1)
  * cldr-plurals-runtime-rb (1.1.0)
  * cliver (0.3.2)
  * cnccs (0.1.6)
  * concurrent-ruby (1.3.4)
  * connection_pool (2.5.0)
  * coradoc (1.1.5)
  * crass (1.0.6)
  * creek (2.6.3)
  * css_parser (1.21.0)
  * csv (3.3.2)
  * date (3.4.1)
  * descriptive_statistics (2.5.1)
  * domain_name (0.6.20240107)
  * down (5.4.2)
  * drb (2.2.1)
  * ebnf (2.4.0)
  * emf2svg (1.4.3)
  * excavate (0.3.7)
  * expressir (2.1.6)
  * extract_ttc (0.3.6)
  * faraday (2.7.12)
  * faraday-net_http (3.0.2)
  * faraday-net_http_persistent (2.3.0)
  * ffi (1.17.1)
  * ffi-compiler2 (2.3.0)
  * ffi-libarchive (1.1.14)
  * ffi-libarchive-binary (0.4.0)
  * fiber-storage (1.0.0)
  * fontist (1.21.2)
  * fuzzy_match (2.1.0)
  * gb-agencies (0.0.7)
  * git (1.19.1)
  * glossarist (2.3.0)
  * graphql (2.4.8)
  * graphql-client (0.25.0)
  * haml (6.3.0)
  * hamster (3.0.0)
  * hashie (4.1.0)
  * hollaback (0.1.1)
  * html2doc (1.8.8)
  * htmlentities (4.3.4)
  * http-cookie (1.0.8)
  * i18n (1.14.6)
  * ieee-idams (0.2.11)
  * iev (0.3.5)
  * image_size (3.4.0)
  * iso-639 (0.3.8)
  * iso639 (1.3.3)
  * isodoc (2.12.7)
  * isodoc-i18n (1.3.1)
  * isoics (0.1.13)
  * japanese_calendar (0.4.2)
  * json (2.9.1)
  * json-canonicalization (1.0.0)
  * json-ld (3.3.2)
  * json-ld-preloaded (3.3.1)
  * latex-decode (0.4.0)
  * ld-patch (3.3.0)
  * libmspack (0.11.0)
  * lightly (0.4.0)
  * link_header (0.0.8)
  * linkeddata (3.3.1)
  * liquid (5.6.0)
  * loc_mods (0.2.5)
  * logger (1.6.4)
  * lutaml (0.9.25)
  * lutaml-model (0.5.1)
  * lutaml-path (0.1.0)
  * marcel (1.0.4)
  * mathml2asciimath (0.0.14)
  * matrix (0.4.2)
  * mechanize (2.14.0)
  * metanorma (2.0.10)
  * metanorma-bipm (2.5.10)
  * metanorma-cc (2.5.10)
  * metanorma-cli (1.11.4)
  * metanorma-csa (2.5.10)
  * metanorma-generic (2.7.4)
  * metanorma-iec (2.5.11)
  * metanorma-ieee (1.3.8)
  * metanorma-ietf (3.4.3)
  * metanorma-ietf-data (0.2.0)
  * metanorma-iho (1.0.14)
  * metanorma-iso (2.9.4)
  * metanorma-itu (2.5.12)
  * metanorma-jis (0.4.4)
  * metanorma-ogc (2.6.10)
  * metanorma-plateau (0.1.14)
  * metanorma-plugin-datastruct (0.3.0)
  * metanorma-plugin-glossarist (0.2.3)
  * metanorma-plugin-lutaml (0.7.16)
  * metanorma-standoc (2.10.4)
  * metanorma-utils (1.10.2)
  * mime-types (3.6.0)
  * mime-types-data (3.2025.0107)
  * mini_portile2 (2.8.8)
  * minitest (5.25.4)
  * mml (1.0.1)
  * mn-requirements (0.4.3)
  * mn2pdf (2.11)
  * mnconvert (1.66.0)
  * multi_json (1.15.0)
  * net-ftp (0.1.4)
  * net-http-digest_auth (1.4.1)
  * net-http-persistent (4.0.5)
  * net-protocol (0.2.2)
  * nkf (0.2.0)
  * nokogiri (1.16.8)
  * nokogiri-styles (0.1.2)
  * ogc-gml (1.0.0)
  * optout (0.0.2)
  * oscal (0.1.1)
  * ox (2.14.19)
  * parslet (2.0.0)
  * plane1converter (0.0.1)
  * plist (3.7.2)
  * plurimath (0.8.20)
  * pngcheck (0.3.1)
  * premailer (1.11.1)
  * psych (5.2.2)
  * pubid (0.1.2)
  * pubid-bsi (0.3.4)
  * pubid-ccsds (0.1.6)
  * pubid-cen (0.2.4)
  * pubid-core (1.12.10)
  * pubid-etsi (0.1.0)
  * pubid-iec (0.3.2)
  * pubid-ieee (0.2.2)
  * pubid-iso (0.7.8)
  * pubid-itu (0.1.3)
  * pubid-jis (0.3.2)
  * pubid-nist (0.4.2)
  * public_suffix (6.0.1)
  * racc (1.8.1)
  * rack (3.1.8)
  * rake (13.2.1)
  * rchardet (1.9.0)
  * rdf (3.3.2)
  * rdf-aggregate-repo (3.3.0)
  * rdf-hamster-repo (3.3.0)
  * rdf-isomorphic (3.3.0)
  * rdf-json (3.3.0)
  * rdf-microdata (3.3.0)
  * rdf-n3 (3.3.0)
  * rdf-normalize (0.7.0)
  * rdf-ordered-repo (3.3.0)
  * rdf-rdfa (3.3.0)
  * rdf-rdfxml (3.3.0)
  * rdf-reasoner (0.9.0)
  * rdf-tabular (3.3.0)
  * rdf-trig (3.3.0)
  * rdf-trix (3.3.0)
  * rdf-turtle (3.3.0)
  * rdf-vocab (3.3.2)
  * rdf-xsd (3.3.0)
  * relaton (1.20.0)
  * relaton-3gpp (1.20.0)
  * relaton-bib (1.20.2)
  * relaton-bipm (1.20.3)
  * relaton-bsi (1.20.0)
  * relaton-calconnect (1.20.0)
  * relaton-ccsds (1.20.2)
  * relaton-cen (1.20.0)
  * relaton-cie (1.20.0)
  * relaton-cli (1.20.0)
  * relaton-doi (1.20.0)
  * relaton-ecma (1.20.0)
  * relaton-etsi (1.20.0)
  * relaton-gb (1.20.0)
  * relaton-iana (1.20.0)
  * relaton-iec (1.20.0)
  * relaton-ieee (1.20.0)
  * relaton-ietf (1.20.0)
  * relaton-iev (1.2.0)
  * relaton-iho (1.20.0)
  * relaton-index (0.2.16)
  * relaton-isbn (1.20.0)
  * relaton-iso (1.20.0)
  * relaton-iso-bib (1.20.0)
  * relaton-itu (1.20.0)
  * relaton-jis (1.20.0)
  * relaton-logger (0.2.2)
  * relaton-nist (1.20.0)
  * relaton-oasis (1.20.0)
  * relaton-ogc (1.20.0)
  * relaton-omg (1.20.0)
  * relaton-plateau (1.20.0)
  * relaton-render (0.9.1)
  * relaton-un (1.20.0)
  * relaton-w3c (1.20.0)
  * relaton-xsf (1.20.0)
  * reverse_markdown (2.1.1)
  * rexml (3.4.0)
  * roman-numerals (0.3.0)
  * rouge (4.5.1)
  * rsec (1.0.0)
  * ruby-graphviz (1.2.5)
  * ruby-jing (0.0.3)
  * ruby-ole (1.2.13.1)
  * ruby2_keywords (0.0.5)
  * rubyntlm (0.6.5)
  * rubyzip (2.3.2)
  * scanf (1.0.0)
  * securerandom (0.4.1)
  * sequel (5.88.0)
  * seven-zip (1.4.2)
  * shacl (0.4.1)
  * shale (1.2.1)
  * shex (0.8.0)
  * socksify (1.7.1)
  * sparql (3.3.0)
  * sparql-client (3.3.0)
  * sqlite3 (1.7.3)
  * sterile (1.0.26)
  * stringio (3.1.2)
  * strscan (3.1.2)
  * sxp (1.3.0)
  * sys-proctable (1.3.0)
  * sys-uname (1.3.1)
  * temple (0.10.3)
  * thor (1.3.2)
  * thor-hollaback (0.2.1)
  * thread_safe (0.3.6)
  * tilt (2.5.0)
  * time (0.4.1)
  * timeout (0.4.3)
  * tokenizer (0.3.0)
  * ttfunk (1.8.0)
  * twitter_cldr (6.12.1)
  * tzinfo (2.0.6)
  * tzinfo-data (1.2024.2)
  * unf_ext (0.0.9.1)
  * unicode-types (1.10.0)
  * unicode2latex (0.0.6)
  * unitsml (0.2.9)
  * uri (1.0.2)
  * uuidtools (2.2.0)
  * vectory (0.7.7)
  * webrick (1.9.1)
  * webrobots (0.1.2)
  * word-to-markdown (1.1.9)
  * xmi (0.3.11)
  * yaml (0.4.0)
  * yaml-ld (0.0.3)
  * zeitwerk (2.7.1)
```

method 1 is working, so this is not that urgent, i just wanted to understand which way was correct.   thank you.

**Comment by ReesePlews** [comment]
thanks @ronaldtse you mention

> The build needs to run on git versions in order to work.

is this always the case or just at this time?

**Comment by ronaldtse** [comment]
This will be resolved when the new isodoc and mn-requirements are released.

**Comment by ReesePlews** [comment]
i have confirmed in the release around Jan 20, 2025, with bundle update:

```
PS E:\github\mn-samples-plateau> bundle info mn-requirements
  * mn-requirements (0.4.3)
 PS E:\github\mn-samples-plateau> bundle info metanorma-plateau
  * metanorma-plateau (0.1.15)
 PS E:\github\mn-samples-plateau> bundle info metanorma-standoc
  * metanorma-standoc (2.10.5)
```
 
and doing a local compile that this translation file is now working correctly. 

the location of using it in the document.adoc file is:

`:i18nyaml: config/plateau_i18n-ja.yaml`

the file is shown here:

```
requirements:
   default:
     requirement: 要件
     recommendation: 推奨
     permission: 許可
     obligation: 義務
     subject: 主題
     inherits: 継承
   modspec:
     recommendationtest: 推奨検証
     requirementtest: 要件検証
     permissiontest: 許可検証
     recommendationclass: 推奨分類
     requirementclass: 要件分類
     permissionclass: 許可分類
     abstracttest: 抽象検証
     conformanceclass: 適合分類
     conformancetest: 適合性検証
     targettype: 対象の種類
     target: 対象
     testpurpose: 検証目的
     testmethod: 検証方法
     dependency: 前提条件
     indirectdependency: 間接的な前提条件
     identifier: ID
     included_in: 分類
     statement: 明文
     description: 説明
     guidance: ガイダンス
     implements: 実装
     provision: 規定
     
```

this functionality is extremely powerful and does not require any developer assistance to get going now.  thank you for implementing this.

see also: https://github.com/ReesePlews/ribose_discussions/issues/27
