### ISSUE TITLE
Production builds get interrupted by PR builds

### ISSUE THREAD

**Issue by strogonoff** [metanorma/mn-samples-plateau#295]
<img width="692" alt="Screenshot 2025-01-07 at 21 25 21" src="https://github.com/user-attachments/assets/17779092-1de7-4099-8841-0334783024d8" />

Can we allow production builds to continue to completion?

**Comment by ronaldtse** [comment]
@strogonoff there is this section in the build workflow definition:

```yaml
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true
```

You would want to define a good "group" and see if you need cancel-in-progress. Typically for build of pages we cancel in progress builds because it will be replaced immediately later by the subsequent build.
