### ISSUE TITLE
GHA build is not working

### ISSUE THREAD

**Issue by strogonoff** [metanorma/mn-samples-plateau#406]
Firelight step fails with:

```
Segmentation fault (core dumped)
Error: Process completed with exit code 139.
```

Works fine for BIPM on GHA and locally for PLATEAU.

**Comment by strogonoff** [comment]
Possibly related to #408

**Comment by strogonoff** [comment]
I will try building Firelight locally of course but #413 blocks it.

**Comment by ronaldtse** [comment]
Memory usage is a GitHub issue reported on many repos:

* https://github.com/npm/cli/pull/7463
* https://github.com/web-infra-dev/rspack/issues/9141
* https://github.com/expo/expo/issues/32873

Have you tried this suggestion?
https://github.com/actions/runner-images/issues/70#issuecomment-1726775918

```yaml
jobs:
  foo:
    steps:
      - name: "Bar"
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
        run: npm start
```
